Confirm only a tx that wasn't already confirmed
MetaMask/smart-transactions-controller pull request #301
Opened 2024-03-19 14:20 UTC by dan437

## Description
When used outside of Swaps, the TransactionController usually confirms completed smart transactions, unless a user closes a browser before a smart transaction is completed. We only want to call the `confirmExternalTransaction` function if a transaction wasn't already confirmed.

2024-03-19 14:36 UTC, dan437 commented on package.json
> +    "@babel/runtime": "^7.24.1",
Great question! I've tried to use `import { TransactionStatus } from '@metamask/transaction-controller';`, but without this 2 tests were failing with a missing dependency on Babel.

2024-03-19 15:18 UTC, infiniteflower submitted a review, later dismissed

2024-03-20 16:21 UTC, infiniteflower requested changes

2024-03-20 16:21 UTC, infiniteflower commented on src/SmartTransactionsController.ts
> +      getTransactions: any;
Can we make this type the same as `this.getRegularTransactions`

2024-03-27 16:09 UTC, infiniteflower approved these changes

2024-03-27 16:13 UTC, merged